---
title: "Executive Summary"
author: "Miguel Conde"
date: "30 de mayo de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En este artículo vamos a analizar la **intensidad** de las actividades de I+D y el **volumen de inversión** en las mismas:

* Desde 2004 a 2015.
* Con foco en los países de la UE pero teniendo en cuenta a otros importantes actores como EEUU, China, Corea del Sur, etc.
* Desglosando los datos según los *performace sectors*  que distingue el [Manual Frascati][MF] de la OECDE (Empresas Comerciales, Administraciones Públicas, Educación Superior, Privado Sin Ánimo de Lucro y Exterior).

Los datos que se manejan son los siguientes:

* De [Eurostat][EUS]:
    + La **intensidad** de las actividades de I+D se mide mediante el Gasto en I+D expresado como porcentaje del PIB.
    + El **volumen de inversión en I+D** se analiza según los procentajes de tal volumen provenientes de cada *performace* sector.
  
* Del [Fondo Monetario Internacional][FMI]
    + **Producto interior bruto (PIB) [total][FMI2] y [per capita][pcGDP_PPP], a valores de [paridad de poder adquisitivo (PPA)][PPA]**, expresado en *[international dollars][IDOL]*. De esta manera es factible comparar PIBs entre países, ya que se tienen en cuenta tanto las diferencias en nivel de vida y tasas de inflación entre ellos.
    
Nuestro interés se centrará en:

* La **relación** entre **inversión en I+D** y **PIB per capita**.
* La influencia que puedan tener los porcentajes de **inversión pública** e **inversión privada** en la **intensidad total de las actividades de I+D**.
* Las implicaciones para España.

El plan del artículo y sus principales conclusiones son las siguientes:

1. Comenzaremos con la **motivación** para realizar este estudio.

2. Continuaremos reseñando los datos que hemos utilizado en él.

3. Iniciaremos el estudio explorando la evolución de la I+D en España durante los años 2004-15, tanto en términos relativos como absolutos.

    * De 2008 a 2011 el incremento de inversión pública, junto a la pequeña bajada en inversión privada (siempre se mantuvo por encima de los niveles de 2007), implicaron un aumento tanto de la intensidad (motivada también por la bajada del PIB) como de la cantidad total empleada en actividades I+D.

    * A partir de 2012 la inversión pública disminuyó un 15% (hasta niveles de 2007), aumentando sin embargo la Exterior y manteniéndose la privada más o menos constante. Esto, junto al aumento del PIB español, se tradujo en una disminución de la intensidad I+D (del 1.35 % en 2009 al 1.21 % en 2015) y del Gasto Total en I+D (un 3% menos que el máximo alcanzado durante la crisis)

2. Continuaremos haciendo una comparativa de la composición de la inversión en I+D, distinguiendo en lo posible fuentes públicas de fuentes privadas de financiación.

    * Hay una correlación positiva muy significativa entre inversión privada e intensidad I+D.
    
    * La correlación entre inversión pública e intensidad I+D es significativa y negativa.
    
    * España obtiene fondos para inversión en I+D de manera acorde a su media-baja Intensidad I+D, es decir, con un bajo componente de fondos privados, unos 10 puntos porcentuales por debajo de la media europea y más de 15 puntos porcentuales por debajo de los países de mayor Intensidad I+D.
    

3. Veremos un *mapa estratégico*, en términos de PIB per capita e intensidad de las actividades de I+D, de la situación relativa de los países analizados.

**Conclusiones principales**

4. Terminaremos con una serie de **conclusiones aplicables a España**.




[MF]: <http://www.oecd-ilibrary.org/science-and-technology/frascati-manual-2015_9789264239012-en;jsessionid=2512lbhn8gnuf.x-oecd-live-02> "Manual Frascati"
[EUS]: <http://ec.europa.eu/eurostat/web/science-technology-innovation/data/main-tables> "Eurostat"
[FMI]: <https://en.wikipedia.org/wiki/International_Monetary_Fund>
[FMI2]: <https://en.wikipedia.org/wiki/List_of_countries_by_past_and_projected_GDP_(PPP)> "List of countries by past and projected GDP (PPP)"
[PPA]: <https://es.wikipedia.org/wiki/Paridad_de_poder_adquisitivo>
[IDOL]: <https://es.wikipedia.org/wiki/Dolar_internacional>
[pcGDP_PPP]: <https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(PPP)_per_capita>